spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://192.168.254.123:1433;databaseName=dbsistema;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=183729*a
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.database=sql_server
spring.jpa.hibernate.ddl-auto=update
app.jwt-secret=ZjgyZjA0OWIwNmFiMGJhYTI1OTRjNjBiOTMwNTQ4ZjhlMjIxNTY5YWNiNTYxZDQyZjQ3Y2E3NzNiNGNmOWZhNmViN2RjYWVkOTgxMGM0OTMyZTRlNTJkM2I4ZmU3NmJmZTllNWE3ZmE2YjQxM2ZlNzJjY2YyOTkzMjQ2OGM2YmQ2NTExZGYyZWE0ZDE2NTcwOTgwYWZhNzljNDA2MTgyMDVlYTg3NDI5YjlkMmRmYzliNjA1NjEwZGU1MTQ0MTlmYzA4OTFmY2JlNGMwODkyYjdkYWQ3MDBmZTQ1M2M3NzkwZWY4NWIxN2QzY2IxMjk5NWY4MmQwYThjMjU1ZmM2Y2IwN2M5ZTAxNDc3MTFlMmRlYTNmOTE4MWJhNzcwMjRjNzAwNmJkODQ5Nzk5MzllZDYyYThlYzlkYjQ0MzM2NzljYmMyZmMwMDZmZGY0MDc1ZmNiMmJhYmNjODk5Y2YyYTc3Nzc0NzQ1NjNlM2U3NWI4NzllZWRhNzM5MDkyMzkwZmU5YWUxOTg2YmZlMTA2ZGUzZDkyZGQ3MzhlZWYxNzY4Zjc4Y2E1MWZhMmEwNzQyMDI2ZjUwZTI3YWUwZDY5YjA4MmM3YWZkY2E5MTliM2Y5YTJiNmVjNTE2YTNkZTUzMDI3ZTdlZmYwOTg2M2MwNjNjOWUyOTRmYWI4ODNiNmI=
app-jwt-expiration-milliseconds=604800000
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration